### ISSUE TITLE
should ignore provider setting when enabled is not true

### ISSUE THREAD

**Issue by hieptranquoc** [teracyhq-incubator/teracy-dev-core#30]
```
providers:
    - _id: "0"
      enabled: false
      type: virtualbox
      require_version: ">= 5.2"
      gui: false
      memory: 1024
      description: "%{node_name_prefix} #{Time.now.getutc.to_i}"
```

Ignore setting when enabled: false
