### ISSUE TITLE
should add "weight" for provisioners to change the orders

### ISSUE THREAD

**Issue by hoatle** [teracyhq-incubator/teracy-dev-core#43]
similar to https://github.com/teracyhq/dev/issues/497
ref: https://www.vagrantup.com/docs/provisioning/basic_usage.html#multiple-provisioners

need to work on this: https://github.com/teracyhq-incubator/teracy-dev-core/blob/develop/lib/teracy-dev-core/config/provisioners.rb

If no "weight" is defined, it's 5 by default.

for example:

```yaml
nodes:
  - _id: "0"
    provisioners:
      - _id: '0'
        version: 13.1.31
        type: chef_solo
        log_level: info
        enabled: true
      - _id: '1'
        version: 13.1.31
        type: chef_solo
        log_level: info
        enabled: true
        weight: 6
      - _id: '2'
        version: 13.1.31
        type: chef_solo
        log_level: info
        enabled: true
        weight: 6
      - _id: '3'
        version: 13.1.31
        type: chef_solo
        log_level: info
        enabled: true
        weight: 3
      - _id: '4'
        version: 13.1.31
        type: chef_solo
        log_level: info
        enabled: true
        weight: 4
```

=> the  expected running order (_id) is: 1, 2, 0, 4, 3
