### ISSUE TITLE
should delete "name" key from provisioner settings for options

### ISSUE THREAD

**Issue by hoatle** [teracyhq-incubator/teracy-dev-core#49]
the following settings did not work:

```
  provisioners:
  - _id: certs-ansible
    name: teracy-dev-certs
    type: ansible_local
    verbose: "-vv"
    weight: 8
    enabled: true
    playbook: extensions/teracy-dev-certs/provisioners/ansible/certs.yaml
    extra_vars:
      common_name: k8s.local
      alt_names:
      - accounts.k8s.local
      - login.k8s.local
```

expected: `$ vagrant provision --provision-with teracy-dev-certs` should work

actual:

```
There are errors in the configuration of this machine. Please fix
the following errors and try again:

ansible local provisioner:
* The following settings shouldn't exist: name
```
