### ISSUE TITLE
should have consistent and intuitive config for forwarded_port network config

### ISSUE THREAD

**Issue by hoatle** [teracyhq-incubator/teracy-dev-core#61]
currently supported config:

```yaml
nodes:
  - _id: "core-0"
    vm:
      networks:
        - _id: entry-fwd-port
          type: forwarded_port
          forwarded_ports:
            - _id: entry-fwd-port-0
              guest: 80
              host: 8080
            - _id: entry-fwd-port-1
              guest: 81
              host: 8081
```

we should deprecate the above config and use this config instead:

```yaml
nodes:
  - _id: "core-0"
    vm:
      networks:
        - _id: entry-fwd-port-0
          type: forwarded_port
          guest: 80
          host: 8080
        - _id: entry-fwd-port-1
          type: forwarded_port
          guest: 81
          host: 8081
```
