### ISSUE TITLE
should create ExtensionResources processor to set memory, cpus, etc dynamically

### ISSUE THREAD

**Issue by hoatle** [teracyhq-incubator/teracy-dev-core#64]
- add optional resources for each extension config and create an ExtensionResources processor (the last one in the pipeline to run to calculate and set VM's memory dynamically by overriding each node provider's config)

- users can explicitly set the exact memory, cpus on the provider config (assumed empty by default on the default.providers or node.providers, node.providers has higher precedence)

- resources.{minimum, requests}.{memory, cpus} is optional

example config format without user explict memory/cpus setting:

```yaml
teracy-dev:
  extensions:
    - _id: "entry-iorad-common"
      path:
        extension: teracy-dev-iorad-common
      location:
        git:
          remote:
            origin: git@github.com:iorad/teracy-dev-iorad-common.git
          branch: v0.4.0
      require_version: ">= 0.4.0"
      enabled: true
      resources:
        minimum:
          memory: 1024
          cpus: 1
        requests:
          memory: 1024
          cpus: 1


    - _id: "entry-iorad-app"
      path:
        lookup: workspace
        extension: iorad/teracy-dev-iorad-app/master
        # extension: iorad/teracy-dev-iorad-app/master # the master stable branch
        # extension: iorad/teracy-dev-iorad-app/develop # the develop unstable branch
      location:
        git:
          remote:
            origin: git@github.com:iorad/iorad.git
          branch: develop
      require_version: ">= 0.1.0"
      enabled: false
      resources:
        minimum:
          memory: 3072
          cpus: 0
        requests:
          memory: 3072
          cpus: 3

    - _id: "entry-iorad-extension"
      path:
        lookup: workspace
        extension: iorad-extension/teracy-dev-iorad-extension/master
        # extension: iorad-extension/teracy-dev-iorad-extension/master # the master stable branch
        # extension: iorad-extension/teracy-dev-iorad-extension/develop # the develop unstable branch
      location:
        git:
          remote:
            origin: git@github.com:iorad/iorad-extension.git
          branch: develop
      require_version: ">= 0.1.0"
      enabled: false
      resources:
        minimum:
          memory: 0
          cpus: 0
        requests:
          memory: 1024
          cpus: 0

    - _id: "entry-iorad-video-export"
      path:
        lookup: workspace
        extension: video-export/teracy-dev-iorad-video-export/master
        # extension: video-export/teracy-dev-iorad-video-export/master # the master stable branch
        # extension: video-export/teracy-dev-iorad-video-export/develop # the develop unstable branch
      location:
        git:
          remote:
            origin: git@github.com:iorad/video-export.git
          branch: master
      require_version: ">= 0.1.0"
      enabled: false
      resources:
        minimum:
          memory: 0
          cpus: 0
        requests:
          memory: 1024
          cpus: 0

default:
  providers:
    - _id: "0" # override
      memory: 0 # zero or empty means no set
      cpus: "0" # zero or empty means no set

nodes:
  - _id: "0"
    providers:
      - _id: "0" # override the default by each node
        memory: ""
        cpus: ""
```

Algorithm:

- total minimum memory = total minimum memory of enabled extensions
- total requested memoy = total requested memory of the enabled extensions
- total minimum cpus = total minimum cpus of enabled extensions
- total requested cpus = total requested cpus of enabled extensions
- available memory = calculated available memory for the VMs to run
- available cpus = calculated available cpus for the VMs to run
- explit user-set memory/cpus via default.providers or node.providers (query provider by type to set values correctly: multiple provider support if applicable)
- total minimum must be less than or equal to total requested

- total_available_memory:
  For Mac:
  + max memory can use is 75% * (physic memory - wired memory).
  For Linux:
  + max memory can use is 100% * (free memory + cache + buff )
  for windows:
  + Please use FreePhysicalMemory instead of TotalVisibleMemorySize.

  We know that Linux VM use a lot of free memory for cache, buff. Allocate too much memory for VMs will make host machine out of memory and dev will not able to use their machine

- for each node, we must allocate available_memory basing on the number of nodes, available_cpus is equal to the total_available_cpus respectively:

  + available_memory = total_available_memory / the number of nodes
  + available_cpus = total_available_cpus

  for example:

  total_available_memory: 6000, number of nodes: 2 => each node has floor(6000/2) = 3000 available_memory

  total_available_cpus: 4 => available_cpus for each node: 4

```
if explicit_user_set_memory exists
  if total_minimum_memory <= explicit_user_set_memory <= available_memory:
    set VM's memory to explit_user_set_memory
  else
    abort with error message
else
  if available_memory >= total_requested_memory:
    set VM's memory to total_requested_memory
  else if available_memory >= total_minimum_memory:
    warn
    set VM's memory to available_memory
  else
    abort with error message
```

```
if explicit_user_set_cpus exists
  if total_minimum_cpus <= explicit_user_set_cpus <= available_cpus:
    set VM's cpus to explit_user_set_cpus
  else
    abort with error message
else
  if available_cpus >= total_requested_cpus:
    set VM's cpus to total_requested_cpus
  else if available_cpus >= total_minimum_cpus:
    warn
    set VM's cpus to available_cpus
  else
    abort with error message
```
